In [1]:
import numpy as np

In [2]:
# Task 1 — Create a Tensor
# Create a 1D tensor containing the following sensor readings:
# 25.2, 25.5, 24.9, 26.1, 25.8
# Perform the following:
# Print the tensor. 
# Print its shape. 
# Print the number of dimensions. 
# Print the number of elements. 
# The goal is to make to all remember the  difference between tensor values, shape, size, and number of dimensions.
readings = np.array([25.2, 25.5, 24.9, 26.1, 25.8])
print("Tensor:", readings)
print("Shape:", readings.shape)
print("Number of dimensions (ndim):", readings.ndim)
print("Number of elements (size):", readings.size)

Tensor: [25.2 25.5 24.9 26.1 25.8]
Shape: (5,)
Number of dimensions (ndim): 1
Number of elements (size): 5


In [3]:
# Task 2 — From Vector to Matrix
# Suppose an industrial system has 4 sensors recording measurements for 5 time steps.
# Create the following data:
# Temperature:  [25, 26, 25, 27, 28]
# Pressure:     [101, 102, 101, 103, 104]
# Humidity:     [60, 62, 61, 63, 64]
# Vibration:    [0.2, 0.3, 0.2, 0.4, 0.5]
# Create a tensor with shape:
# (5, 4)
# where:
# rows    → time
# columns → sensors

# Then print:
# shape 
# number of dimensions 
# first time step 
# temperature readings 
# vibration readings 
# Think: What does each axis represent?

temperature = [25, 26, 25, 27, 28]
pressure    = [101, 102, 101, 103, 104]
humidity    = [60, 62, 61, 63, 64]
vibration   = [0.2, 0.3, 0.2, 0.4, 0.5]
 
# rows -> time (5), columns -> sensors (4)
X2 = np.array([temperature, pressure, humidity, vibration]).T  # shape (5,4)
 
print("Shape:", X2.shape)
print("Number of dimensions:", X2.ndim)
print("First time step (X2[0]):", X2[0])
print("Temperature readings (X2[:,0]):", X2[:, 0])
print("Vibration readings (X2[:,3]):", X2[:, 3])

Shape: (5, 4)
Number of dimensions: 2
First time step (X2[0]): [ 25.  101.   60.    0.2]
Temperature readings (X2[:,0]): [25. 26. 25. 27. 28.]
Vibration readings (X2[:,3]): [0.2 0.3 0.2 0.4 0.5]


In [6]:
# Task 3 — Create a 3D Tensor
# Now suppose we monitor 10 machines.
# Each machine has:
# 5 time steps 
# 4 sensors 
# Create a tensor with shape:
# (10, 5, 4)
# Interpret the dimensions as:
# Machine × Time × Sensor
# Then answer using Python:
# What is the temperature reading of machine 3 at time step 2? 
# Extract all sensor readings of machine 5. 
# Extract all machines at time step 1. 
# Extract the readings of sensor 4 from all machines and all time steps. 

np.random.seed(0)
X3 = np.random.randint(20, 100, size=(10, 5, 4)).astype(float)  # Machine x Time x Sensor
 
print("Machine 3, time step 2, sensor(temp):", X3[2, 1, 0])
print("All sensor readings of machine 5, shape:", X3[4].shape)
print("All machines at time step 1, shape:", X3[:, 0, :].shape)
print("Sensor 4 from all machines & all time steps, shape:", X3[:, :, 3].shape)

Machine 3, time step 2, sensor(temp): 20.0
All sensor readings of machine 5, shape: (5, 4)
All machines at time step 1, shape: (10, 4)
Sensor 4 from all machines & all time steps, shape: (10, 5)


In [8]:
# Task 4 — Indexing a Tensor
# Create:
# X = np.arange(24).reshape(2, 3, 4)
# Print X.
# Now investigate:
# X[0]
# X[1]
# X[0, 0]
# X[0, 0, 0]

# Answer:
# What is the shape of X? 
# What does X[0] represent? 
# What does X[0,0] represent? 
# What does X[0,0,0] represent? 

X4 = np.arange(24).reshape(2, 3, 4)
print(X4)
print(X4[0])
print(X4[1])
print(X4[0, 0])
print(X4[0, 0, 0])


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[0 1 2 3]
0


In [9]:
# Task 5 — Slicing
# Using:
# X = np.arange(60).reshape(3, 4, 5)
# Perform:
# Extract the first block: X[0]
# Extract the first row from every block.
# Extract the third element from every row and every block.
# Extract the last two elements along the final dimension. Then print the resulting shapes.

X5 = np.arange(60).reshape(3, 4, 5)
 
first_block = X5[0]                    # first block
first_row_every_block = X5[:, 0, :]    # first row of every block
third_elem_every_row_block = X5[:, :, 2]   # third element of every row & block
last_two_final_dim = X5[:, :, -2:]     # last two elements along final axis
 
print("First block shape:", first_block.shape)
print("First row of every block shape:", first_row_every_block.shape)
print("Third element of every row/block shape:", third_elem_every_row_block.shape)
print("Last two elements along final dim shape:", last_two_final_dim.shape)

First block shape: (4, 5)
First row of every block shape: (3, 5)
Third element of every row/block shape: (3, 4)
Last two elements along final dim shape: (3, 4, 2)


In [10]:
# Task 6 — Image Tensor
# Create a synthetic RGB image tensor:
# Height = 128
# Width = 128
# Channels = 3
# Create:
# image = ...
# with shape: (128, 128, 3)
# Then:
# Print the shape. 
# Extract the red channel. 
# Extract the green channel. 
# Extract the blue channel. 
# Find the maximum pixel value. 
# Find the minimum pixel value. 

np.random.seed(1)
image = np.random.randint(0, 256, size=(128, 128, 3))
 
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
 
print("Shape:", image.shape)
print("Red channel shape:", red.shape)
print("Max pixel value:", image.max())
print("Min pixel value:", image.min())

Shape: (128, 128, 3)
Red channel shape: (128, 128)
Max pixel value: 255
Min pixel value: 0


In [11]:
# Task 7 — Batch of Images
# Now suppose you have 32 RGB images, each of size 128 × 128.
# Create a tensor with shape:
# (32, 128, 128, 3)
# using random values.
# Then:
# Extract the first image. 
# Extract the first 10 images. 
# Extract the red channel from all images. 
# Extract pixel (50, 50) from every image. 
# Print the shape after each operation. 

np.random.seed(2)
batch = np.random.randint(0, 256, size=(32, 128, 128, 3))
 
first_image     = batch[0]
first_10        = batch[:10]
red_all         = batch[:, :, :, 0]
pixel_50_50_all = batch[:, 50, 50, :]
 
print("Batch shape:", batch.shape)
print("First image shape:", first_image.shape)
print("First 10 images shape:", first_10.shape)
print("Red channel of all images shape:", red_all.shape)
print("Pixel (50,50) of every image shape:", pixel_50_50_all.shape)


Batch shape: (32, 128, 128, 3)
First image shape: (128, 128, 3)
First 10 images shape: (10, 128, 128, 3)
Red channel of all images shape: (32, 128, 128)
Pixel (50,50) of every image shape: (32, 3)


In [12]:
# Task 8 — Reshape
# Create:
# X = np.arange(24)
# Reshape it into:
# (4, 6)
# (2, 3, 4)
# (6, 4)
# (24,)
# For each one:
# Print the tensor. 
# Print its shape. 
# Print its number of dimensions. 
# Then try answering:
# Why does reshaping change the shape but not the total number of elements?

X8 = np.arange(24)
for shape in [(4, 6), (2, 3, 4), (6, 4), (24,)]:
    r = X8.reshape(shape)
    print(shape, "-> shape:", r.shape, "| ndim:", r.ndim)


(4, 6) -> shape: (4, 6) | ndim: 2
(2, 3, 4) -> shape: (2, 3, 4) | ndim: 3
(6, 4) -> shape: (6, 4) | ndim: 2
(24,) -> shape: (24,) | ndim: 1


In [13]:
# Task 9 — Reshape vs Transpose
# Create:
# X = np.arange(24).reshape(2, 3, 4)
# Now perform:
# X.reshape(3, 2, 4) and X.transpose(1, 0, 2)
# Compare the results.
# Are these two operations doing the same thing?

X9 = np.arange(24).reshape(2, 3, 4)
reshaped   = X9.reshape(3, 2, 4)
transposed = X9.transpose(1, 0, 2)
 
print("Are they equal?:", np.array_equal(reshaped, transposed))


Are they equal?: False


In [14]:
# Task 10 — Broadcasting
# Create:
# X = np.ones((3, 4))
# and:
# b = np.array([10, 20, 30, 40])
# Calculate: X + b
# Then try: X * b
# Question: Why can a (4,) tensor be combined with a (3,4) tensor?

X10 = np.ones((3, 4))
b10 = np.array([10, 20, 30, 40])
 
add_result = X10 + b10
mul_result = X10 * b10
print(add_result)
print(mul_result)


[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]
[[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]]


In [16]:
# Task 11 — Broadcasting with Sensor Data
# Suppose:
# X.shape = (100, 10)
# represents:
# 100 samples × 10 sensors
# The calibration offset for each sensor is:
# [1.2, 0.8, 1.1, 0.5, 0.9, 1.0, 0.7, 1.3, 0.6, 0.4]
# Create the tensor and subtract the calibration offsets.
# Your output should remain:
# (100, 10)
# Goal: See broadcasting in an actual engineering problem.

np.random.seed(3)
X11 = np.random.randn(100, 10) + 5  # 100 samples x 10 sensors
offsets = np.array([1.2, 0.8, 1.1, 0.5, 0.9, 1.0, 0.7, 1.3, 0.6, 0.4])
 
calibrated = X11 - offsets
print("Calibrated shape:", calibrated.shape)


Calibrated shape: (100, 10)


In [19]:
# Task 12 — Tensor Aggregation
# Create:
# X = np.random.randn(100, 20, 5)
# Interpret it as:
# 100 machines
# 20 time steps
# 5 sensors
# Calculate:
# Mean across time. 
# Mean across sensors. 
# Mean across machines. 
# Maximum sensor value across time. 
# Standard deviation across time. 
# Predict the resulting shape before running the code.

X12 = np.random.randn(100, 20, 5)  # machines, time, sensors
 
mean_time            = X12.mean(axis=1)   # average over time
mean_sensors         = X12.mean(axis=2)   # average over sensors
mean_machines        = X12.mean(axis=0)   # average over machines
max_sensor_over_time = X12.max(axis=1)
std_time             = X12.std(axis=1)
 
print(mean_time.shape, mean_sensors.shape, mean_machines.shape,
      max_sensor_over_time.shape, std_time.shape)


(100, 5) (100, 20) (20, 5) (100, 5) (100, 5)


In [20]:
# Task 13 — Normalize a Tensor
# Create sensor data:
# X = np.random.randn(100, 20, 5)
# Calculate the mean and standard deviation for each sensor.
# Normalize the tensor using:
#  xnormalized=x-μ
# Then verify:
# mean ≈ 0
# standard deviation ≈ 1
X13 = np.random.randn(100, 20, 5)
 
mu    = X13.mean(axis=(0, 1), keepdims=True)   # per-sensor mean, shape (1,1,5)
sigma = X13.std(axis=(0, 1), keepdims=True)    # per-sensor std,  shape (1,1,5)
 
X13_norm = (X13 - mu) / sigma
print("Normalized mean:", X13_norm.mean(axis=(0, 1)))
print("Normalized std: ", X13_norm.std(axis=(0, 1)))


Normalized mean: [-1.05471187e-17  3.44169138e-18 -8.21565038e-17 -4.08145739e-17
 -1.09356968e-17]
Normalized std:  [1. 1. 1. 1. 1.]


In [21]:
# Task 14 — Flattening
# Create an image:
# (28, 28, 3)
# Flatten it into:
# (2352,)
# Then create a batch of 64 images:
# (64, 28, 28, 3)
# Flatten each image while keeping the batch dimension.
# Expected shape: 	(64, 2352)
# Why shouldn't we simply flatten the entire tensor into (150528,) when working with a batch?
img14 = np.random.randint(0, 256, size=(28, 28, 3))
flat_single = img14.flatten()
print("Single image flatten shape:", flat_single.shape)
 
batch14 = np.random.randint(0, 256, size=(64, 28, 28, 3))
flat_batch = batch14.reshape(batch14.shape[0], -1)   # keep batch dim
print("Batch flatten (keep batch dim) shape:", flat_batch.shape)


Single image flatten shape: (2352,)
Batch flatten (keep batch dim) shape: (64, 2352)


In [22]:
# Task 15 — Concatenation
# Suppose a model produces two feature tensors:
# Visual features:
# (32, 128)

# Sensor features:
# (32, 64)
# Combine them into a single feature tensor.
# Expected result:
# (32, 192)
# Use tensor concatenation.
# Then explain:
# Why can we concatenate along the feature dimension but not arbitrarily along every dimension?

visual = np.random.randn(32, 128)   # 32 samples x 128 visual features
sensor = np.random.randn(32, 64)    # 32 samples x 64 sensor features
 
combined = np.concatenate([visual, sensor], axis=1)
print("Combined shape:", combined.shape)


Combined shape: (32, 192)


In [28]:
# Task 16 — Practical Mini Challenge: Sensor Dataset
# Create a synthetic dataset representing:
# 500 machines
# 60 time steps
# 8 sensors

# Therefore:

# X.shape = (500, 60, 8)

# Perform the following:
# Extract machine 10. 
# Extract the first 20 time steps. 
# Extract sensor 5 from all machines. 
# Calculate the average value of every sensor. 
# Calculate the average value at every time step. 
# Find the machine with the highest average sensor reading. 
# Normalize each sensor. 
# Split the tensor into: 
# Training: 400 machines 
# Testing: 100 machines 

X16 = np.random.randn(500, 60, 8) * 10 + 50   # machines, time, sensors
print('X16.shape:', X16.shape)
 
machine_10       = X16[10]
print(machine_10.shape)
first_20_steps      = X16[:, :20, :]
print(first_20_steps.shape)
sensor_5_all     = X16[:, :, 5]
print(sensor_5_all.shape) 
avg_per_sensor   = X16.mean(axis=(0, 1))
print(avg_per_sensor) 
avg_per_timestep = X16.mean(axis=(0, 2))
print(avg_per_timestep)  
machine_avg      = X16.mean(axis=(1, 2))
highest_machine     = np.argmax(machine_avg)
print('Highest average machine:', highest_machine)
 
mu16, sigma16 = X16.mean(axis=(0,1), keepdims=True), X16.std(axis=(0,1), keepdims=True)
X16_norm = (X16 - mu16) / sigma16
X_train, X_test = X16[:400], X16[400:]

print(X_train.shape, X_test.shape)


X16.shape: (500, 60, 8)
(60, 8)
(500, 20, 8)
(500, 60)
[50.00382417 50.02956699 50.00922553 50.03948057 49.97532023 49.94966046
 50.06430554 50.0390875 ]
[50.29796124 50.01338059 49.90430264 50.20506366 49.81982414 50.07154077
 50.08642843 49.82583967 49.94357765 49.87640514 49.9939317  50.0083975
 50.0076995  50.14722333 50.04640546 50.31196025 49.73920964 50.12476711
 50.12355551 49.81180768 50.02186883 50.02464282 50.17704593 50.14999104
 50.03334478 49.84980119 49.87901526 50.13670757 50.05945131 49.98326945
 50.26292531 49.90706269 50.1476558  50.0786432  49.86757676 50.10824013
 49.81286311 50.00322114 49.90098755 49.83951951 49.99027301 50.03378008
 49.97838337 49.89854854 49.70049046 50.02049705 49.99580471 50.03237801
 49.99553653 49.82079324 50.10089284 50.18606828 50.02581232 50.0696187
 50.13224092 50.11873662 49.86475702 50.16220303 49.95209204 50.14651074]
Highest average machine: 111
(400, 60, 8) (100, 60, 8)


In [30]:
# Task 17 — PyTorch 

# import torch
# X = torch.arange(24).reshape(2, 3, 4)

# print(X)
# print(X.shape)
# print(X.ndim)
# print(X.numel())

# Then try:
# X = torch.randn(32, 100, 768)

# What could these three dimensions represent?

import torch
 
X = torch.arange(24).reshape(2, 3, 4)
print(X)
print(X.shape)
print(X.ndim)
print(X.numel())
 
X2 = torch.randn(32, 100, 768)
print(X2.shape)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
3
24
torch.Size([32, 100, 768])
